### ISSUE TITLE
not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by GrahamboJangles** [achillesrasquinha/bulbea#24]
`scaler, Xtrain, Xtest, ytrain, ytest = split(share, 'Close', normalize = True)`
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-6857080bc17c> in <module>()
----> 1 scaler, Xtrain, Xtest, ytrain, ytest = split(share, 'Close', normalize = True)

ValueError: not enough values to unpack (expected 5, got 4)
```

**Comment by dogabasaran** [comment]
If you look at the split function, you'll see it only returns 4 values. Delete scaler.

**Comment by yanzhipingliu** [comment]
How can I use split function?

>>> Xtrain, Xtest, ytrain, ytest = split(share, 'Close', normalize = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'split' is not defined
>>> Xtrain, Xtest, ytrain, ytest = bb.split(share, 'Close', normalize = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bulbea' has no attribute 'split'
