### ISSUE TITLE
bulbea crashes when executing "share = bb.Share('YAHOO', 'GOOGL')" in python2.7

### ISSUE THREAD

**Issue by realPaulTec** [achillesrasquinha/bulbea#39]
Hello, today I attempted to install the library and run into an issue.
after importing bulbea with `>>> import bulbea as bb` everything seamed normal but when trying to run 
`>>> share = bb.Share('YAHOO', 'GOOGL')` 
I get this following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bulbea/entity/share.py", line 166, in __init__
    message = Color.warn("Environment variable {envvar} for Quandl hasn't been set. A maximum of {max_calls} calls per day can be made. Visit {url} to get your API key.".format(envvar = envvar, max_calls = QUANDL_MAX_DAILY_CALLS, url = ABSURL_QUANDL))
TypeError: unbound method warn() must be called with Color instance as first argument (got str instance instead)
`
Now I have no clue what exactly went wrong or why it isn't working, can someone help me with this?

**Comment by codepharmer** [comment]
As [achillesrasquinha
](https://github.com/achillesrasquinha/) mentioned on a different issue thread, try
```share = bb.Share(source = 'WIKI', ticker = 'GOOGL')```
