### ISSUE TITLE
Failed cleaning build dir for cryptography

### ISSUE THREAD

**Issue by alexon1234** [achillesrasquinha/bulbea#5]
When I am trying to install the requirements, it appear this message.
It is normal or is something missing?

**Comment by achillesrasquinha** [comment]
What OS are you installing it on? I remember coming across such an error.

**Comment by alexon1234** [comment]
Linux,  Ubuntu 64bits

**Comment by achillesrasquinha** [comment]
Try installing the dependencies.
```console
$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev
```

Then go ahead and install `cryptography`
```console
$ pip install cryptography
```

**Comment by alexon1234** [comment]
Thank you very much

**Comment by alexon1234** [comment]
Thanks for the information, it worked. Now, I was doing a test, but I have get this information message even that I set up the API Key in the app.py

File "/home/alex/bulbea/bulbea/entity/share.py", line 167, in __init__
    message = Color.warn("Environment variable {envvar} for Quandl hasn't been set. A maximum of {max_calls} calls per day can be made. Visit {url} to get your API key.".format(envvar = envvar, max_calls = QUANDL_MAX_DAILY_CALLS, url = ABSURL_QUANDL))

**Comment by achillesrasquinha** [comment]
This is probably a warning you receive each time you call a `Share` object. You may or may not set the API key. But first, is this a warning or does the program break?

**Comment by alexon1234** [comment]
It breaks and no data displays

**Comment by JingweiTu** [comment]
I have this problem but for macOS 10.12.6. Any solutions?

**Comment by yanzhipingliu** [comment]
I have the same problem. Do we have a solution or walkaround for it?

>>> share = bb.Share('NEE', 'TSLA')
C:\tools\Python38\lib\site-packages\bulbea-0.1.0-py3.8.egg\bulbea\entity\share.py:168: UserWarning: ←[01m←[33mEnvironment variable BULBEA_QUANDL_API_KEY for Quandl hasn't been set. A maximum of 50000 calls per day can be made. Visit https://www.quandl.com to get your API key.←[0m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tools\Python38\lib\site-packages\bulbea-0.1.0-py3.8.egg\bulbea\entity\share.py", line 175, in __init__
  File "C:\tools\Python38\lib\site-packages\bulbea-0.1.0-py3.8.egg\bulbea\entity\share.py", line 187, in update
  File "C:\tools\Python38\lib\site-packages\quandl\get.py", line 48, in get
    data = Dataset(dataset_args['code']).data(params=kwargs, handle_column_not_found=True)
  File "C:\tools\Python38\lib\site-packages\quandl\model\dataset.py", line 47, in data
    return Data.all(**updated_options)
  File "C:\tools\Python38\lib\site-packages\quandl\operations\list.py", line 15, in all
    r = Connection.request('get', path, **options)
  File "C:\tools\Python38\lib\site-packages\quandl\connection.py", line 38, in request
    return cls.execute_request(http_verb, abs_url, **options)
  File "C:\tools\Python38\lib\site-packages\quandl\connection.py", line 50, in execute_request
    cls.handle_api_error(response)
  File "C:\tools\Python38\lib\site-packages\quandl\connection.py", line 114, in handle_api_error
    raise klass(message, resp.status_code, resp.text, resp.headers, code)
quandl.errors.quandl_error.NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.
