### ISSUE TITLE
Help Needed: (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again

### ISSUE THREAD

**Issue by moibilegite** [achillesrasquinha/bulbea#9]
Hi, 

When I try to follow the example, I have the following errors. Please help.

>>> share = bb.Share('YAHOO', 'GOOGL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edison/bulbea/bulbea/entity/share.py", line 175, in __init__
    self.update(start = start, end = end, latest = latest, cache = cache)
  File "/home/edison/bulbea/bulbea/entity/share.py", line 189, in update
    code     = self.ticker
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/get.py", line 48, in get
    data = Dataset(dataset_args['code']).data(params=kwargs, handle_column_not_found=True)
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/model/dataset.py", line 47, in data
    return Data.all(**updated_options)
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/operations/list.py", line 14, in all
    r = Connection.request('get', path, **options)
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/connection.py", line 36, in request
    return cls.execute_request(http_verb, abs_url, **options)
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/connection.py", line 44, in execute_request
    cls.handle_api_error(response)
  File "/home/edison/.local/lib/python3.5/site-packages/quandl/connection.py", line 85, in handle_api_error
    raise klass(message, resp.status_code, resp.text, resp.headers, code)
quandl.errors.quandl_error.NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.

Thanks.
Best Regards,
Edison

**Comment by khaman1** [comment]
I got the same error :(

**Comment by MichaelFriedberg** [comment]
Me as well

**Comment by achillesrasquinha** [comment]
Sorry to keep y'all bothering on this. I'll get back to this project at the earliest. I'll have this fixed (although I'll be happy for contributions). Engrossed in a lot of work right now, having the other things wrapped up!

**Comment by MichaelFriedberg** [comment]
@achillesrasquinha What do I need to do to contribute?

**Comment by achillesrasquinha** [comment]
Fork it and work on your repository. If things fix, send in a PR, I'll review and patch it. I just came to realize `pandas-datareader` has Quandl support so I'll have Quandl removed soon with the next update and use `pandas-datareader` instead. We're then open to more options.

**Comment by MichaelFriedberg** [comment]
@achillesrasquinha but didnt you say pandas-datareader is dependent on  Quandl?

**Comment by achillesrasquinha** [comment]
I'm not sure but I guess this is a Quandl Error. I did a code check - https://www.quandl.com/data/YAHOO/GOOGL. Maybe the databases have been updated.

Try WIKI as a source
```python
share = bb.Share('WIKI', 'GOOGL')
```

Let me know if this works.

**Comment by achillesrasquinha** [comment]
@MichaelFriedberg The `pandas-datareader` has multiple data sources. It's good to have many using a single interface. I'm keen to have intraday values too (but unaware of sources). Let me know if you know any. Quandl's premium databases do have them, hence I used Quandl initially. Now that `pandas-datareader` wraps Quandl (along with many other sources), no harm having that embedded.

**Comment by vital987** [comment]
The format is ```bb.Share('QUANDL_DATASET', 'STOCK_CODE_IN_DATASET')```, their are many data sets in Quandl such as WIKI, [BSE](https://www.quandl.com/data/BSE), [NSE](https://www.quandl.com/data/NSE-National-Stock-Exchange-of-India), etc. WIKI is deprecated in 2018 so it will not show latest data. NSE & EOD are premium, you can search for datasets [here](https://www.quandl.com/search?filters=%5B%22Free%22%5D), then go in documentation of that data set and download it's codes csv, and enter the data as per your requirements.
